---
- name: Install MySQL packages
  yum: name={{ item }} state=present
  with_items:
   - mysql-server
   - mysql-devel
   - MySQL-python
   # - libselinux-python
   # - libsemanage-python

- name: Install the Python MySQLB module
  pip: name=MySQL-python
  become: yes

# - name: Configure SELinux to start mysql on any port
#   seboolean: name=mysql_connect_any state=true persistent=yes
#   when: ansible_selinux.status == "enabled"

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify: 
  - restart mysql

- name: Start Mysql Service
  service: name=mysqld state=started enabled=yes
